# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Apps\DEV\PROJECTS\KoHighlights\gui_about.ui'
#
# Created: Tue Sep 19 17:26:05 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.setWindowModality(QtCore.Qt.ApplicationModal)
        About.resize(480, 560)
        About.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        About.setModal(False)
        self.verticalLayout = QtGui.QVBoxLayout(About)
        self.verticalLayout.setObjectName("verticalLayout")
        self.about_tabs = QtGui.QTabWidget(About)
        self.about_tabs.setTabShape(QtGui.QTabWidget.Rounded)
        self.about_tabs.setObjectName("about_tabs")
        self.info_tab = QtGui.QWidget()
        self.info_tab.setObjectName("info_tab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.info_tab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea_2 = QtGui.QScrollArea(self.info_tab)
        self.scrollArea_2.setStyleSheet("QScrollArea {background-color:transparent;}")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 454, 483))
        self.scrollAreaWidgetContents_2.setStyleSheet("background-color:transparent;")
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.setContentsMargins(6, 0, 6, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.text_lbl = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.text_lbl.setText("")
        self.text_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.text_lbl.setWordWrap(True)
        self.text_lbl.setOpenExternalLinks(True)
        self.text_lbl.setObjectName("text_lbl")
        self.verticalLayout_6.addWidget(self.text_lbl)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.scrollArea_2)
        self.about_tabs.addTab(self.info_tab, "")
        self.log_tab = QtGui.QWidget()
        self.log_tab.setObjectName("log_tab")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.log_tab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.log_txt = QtGui.QPlainTextEdit(self.log_tab)
        self.log_txt.setFrameShape(QtGui.QFrame.WinPanel)
        self.log_txt.setDocumentTitle("")
        self.log_txt.setUndoRedoEnabled(False)
        self.log_txt.setReadOnly(True)
        self.log_txt.setPlainText("")
        self.log_txt.setObjectName("log_txt")
        self.verticalLayout_8.addWidget(self.log_txt)
        self.about_tabs.addTab(self.log_tab, "")
        self.verticalLayout.addWidget(self.about_tabs)
        self.btn_box = QtGui.QFrame(About)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_box.sizePolicy().hasHeightForWidth())
        self.btn_box.setSizePolicy(sizePolicy)
        self.btn_box.setFrameShape(QtGui.QFrame.StyledPanel)
        self.btn_box.setFrameShadow(QtGui.QFrame.Raised)
        self.btn_box.setObjectName("btn_box")
        self.horizontalLayout = QtGui.QHBoxLayout(self.btn_box)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.updates_btn = QtGui.QPushButton(self.btn_box)
        self.updates_btn.setObjectName("updates_btn")
        self.horizontalLayout.addWidget(self.updates_btn)
        spacerItem = QtGui.QSpacerItem(175, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.close_btn = QtGui.QPushButton(self.btn_box)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout.addWidget(self.close_btn)
        self.verticalLayout.addWidget(self.btn_box)

        self.retranslateUi(About)
        self.about_tabs.setCurrentIndex(0)
        QtCore.QObject.connect(self.close_btn, QtCore.SIGNAL("clicked()"), About.close)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        About.setWindowTitle(QtGui.QApplication.translate("About", "About KoHighlights", None, QtGui.QApplication.UnicodeUTF8))
        self.about_tabs.setTabText(self.about_tabs.indexOf(self.info_tab), QtGui.QApplication.translate("About", "Information", None, QtGui.QApplication.UnicodeUTF8))
        self.about_tabs.setTabText(self.about_tabs.indexOf(self.log_tab), QtGui.QApplication.translate("About", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.updates_btn.setToolTip(QtGui.QApplication.translate("About", "Check online for an updated version", None, QtGui.QApplication.UnicodeUTF8))
        self.updates_btn.setText(QtGui.QApplication.translate("About", "Check for Updates", None, QtGui.QApplication.UnicodeUTF8))
        self.close_btn.setText(QtGui.QApplication.translate("About", "Close", None, QtGui.QApplication.UnicodeUTF8))

import images_rc
