# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Apps\DEV\PROJECTS\KoHighlights\gui_main.ui'
#
# Created: Fri Feb 22 03:09:24 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Base(object):
    def setupUi(self, Base):
        Base.setObjectName("Base")
        Base.resize(619, 418)
        Base.setWindowTitle("KoHighlights")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/stuff/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Base.setWindowIcon(icon)
        Base.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        Base.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtGui.QWidget(Base)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.views = QtGui.QStackedWidget(self.centralwidget)
        self.views.setObjectName("views")
        self.books_pg = QtGui.QWidget()
        self.books_pg.setObjectName("books_pg")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.books_pg)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtGui.QSplitter(self.books_pg)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.file_table = DropTableWidget(self.splitter)
        self.file_table.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.file_table.setFrameShape(QtGui.QFrame.WinPanel)
        self.file_table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.file_table.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.file_table.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.file_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.file_table.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.file_table.setCornerButtonEnabled(False)
        self.file_table.setColumnCount(6)
        self.file_table.setObjectName("file_table")
        self.file_table.setColumnCount(6)
        self.file_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.file_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.file_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.file_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.file_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.file_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.file_table.setHorizontalHeaderItem(5, item)
        self.file_table.horizontalHeader().setHighlightSections(False)
        self.file_table.horizontalHeader().setMinimumSectionSize(22)
        self.file_table.horizontalHeader().setSortIndicatorShown(True)
        self.file_table.verticalHeader().setDefaultSectionSize(22)
        self.file_table.verticalHeader().setHighlightSections(True)
        self.file_table.verticalHeader().setMinimumSectionSize(22)
        self.frame = QtGui.QFrame(self.splitter)
        self.frame.setFrameShape(QtGui.QFrame.WinPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtGui.QWidget(self.frame)
        self.header.setObjectName("header")
        self.horizontalLayout = QtGui.QHBoxLayout(self.header)
        self.horizontalLayout.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fold_btn = QtGui.QToolButton(self.header)
        self.fold_btn.setStyleSheet("QToolButton{border:none;}")
        self.fold_btn.setCheckable(True)
        self.fold_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.fold_btn.setArrowType(QtCore.Qt.DownArrow)
        self.fold_btn.setObjectName("fold_btn")
        self.horizontalLayout.addWidget(self.fold_btn)
        self.frame_2 = QtGui.QFrame(self.header)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtGui.QFrame.HLine)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.header)
        self.book_info = QtGui.QFrame(self.frame)
        self.book_info.setFrameShape(QtGui.QFrame.StyledPanel)
        self.book_info.setFrameShadow(QtGui.QFrame.Raised)
        self.book_info.setObjectName("book_info")
        self.gridLayout = QtGui.QGridLayout(self.book_info)
        self.gridLayout.setContentsMargins(6, 0, 6, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.status_txt = QtGui.QLineEdit(self.book_info)
        self.status_txt.setReadOnly(True)
        self.status_txt.setObjectName("status_txt")
        self.gridLayout.addWidget(self.status_txt, 4, 4, 1, 1)
        self.time_lbl = QtGui.QLabel(self.book_info)
        self.time_lbl.setObjectName("time_lbl")
        self.gridLayout.addWidget(self.time_lbl, 4, 0, 1, 1)
        self.title_lbl = QtGui.QLabel(self.book_info)
        self.title_lbl.setObjectName("title_lbl")
        self.gridLayout.addWidget(self.title_lbl, 0, 0, 1, 1)
        self.series_lbl = QtGui.QLabel(self.book_info)
        self.series_lbl.setObjectName("series_lbl")
        self.gridLayout.addWidget(self.series_lbl, 2, 0, 1, 1)
        self.author_txt = QtGui.QLineEdit(self.book_info)
        self.author_txt.setReadOnly(True)
        self.author_txt.setObjectName("author_txt")
        self.gridLayout.addWidget(self.author_txt, 1, 2, 1, 3)
        self.author_lbl = QtGui.QLabel(self.book_info)
        self.author_lbl.setObjectName("author_lbl")
        self.gridLayout.addWidget(self.author_lbl, 1, 0, 1, 1)
        self.title_txt = QtGui.QLineEdit(self.book_info)
        self.title_txt.setReadOnly(True)
        self.title_txt.setObjectName("title_txt")
        self.gridLayout.addWidget(self.title_txt, 0, 2, 1, 3)
        self.pages_txt = QtGui.QLineEdit(self.book_info)
        self.pages_txt.setReadOnly(True)
        self.pages_txt.setObjectName("pages_txt")
        self.gridLayout.addWidget(self.pages_txt, 3, 4, 1, 1)
        self.pages_lbl = QtGui.QLabel(self.book_info)
        self.pages_lbl.setObjectName("pages_lbl")
        self.gridLayout.addWidget(self.pages_lbl, 3, 3, 1, 1)
        self.time_txt = QtGui.QLineEdit(self.book_info)
        self.time_txt.setReadOnly(True)
        self.time_txt.setObjectName("time_txt")
        self.gridLayout.addWidget(self.time_txt, 4, 2, 1, 1)
        self.lang_txt = QtGui.QLineEdit(self.book_info)
        self.lang_txt.setReadOnly(True)
        self.lang_txt.setObjectName("lang_txt")
        self.gridLayout.addWidget(self.lang_txt, 3, 2, 1, 1)
        self.lang_lbl = QtGui.QLabel(self.book_info)
        self.lang_lbl.setObjectName("lang_lbl")
        self.gridLayout.addWidget(self.lang_lbl, 3, 0, 1, 1)
        self.status_lbl = QtGui.QLabel(self.book_info)
        self.status_lbl.setObjectName("status_lbl")
        self.gridLayout.addWidget(self.status_lbl, 4, 3, 1, 1)
        self.series_txt = QtGui.QLineEdit(self.book_info)
        self.series_txt.setReadOnly(True)
        self.series_txt.setObjectName("series_txt")
        self.gridLayout.addWidget(self.series_txt, 2, 2, 1, 3)
        self.verticalLayout.addWidget(self.book_info)
        self.highlights_list = QtGui.QListWidget(self.frame)
        self.highlights_list.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.highlights_list.setFrameShape(QtGui.QFrame.WinPanel)
        self.highlights_list.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.highlights_list.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.highlights_list.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.highlights_list.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.highlights_list.setWordWrap(True)
        self.highlights_list.setObjectName("highlights_list")
        self.verticalLayout.addWidget(self.highlights_list)
        self.verticalLayout_3.addWidget(self.splitter)
        self.views.addWidget(self.books_pg)
        self.highlights_pg = QtGui.QWidget()
        self.highlights_pg.setObjectName("highlights_pg")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.highlights_pg)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.highlight_table = QtGui.QTableWidget(self.highlights_pg)
        self.highlight_table.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.highlight_table.setFrameShape(QtGui.QFrame.WinPanel)
        self.highlight_table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.highlight_table.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.highlight_table.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.highlight_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.highlight_table.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.highlight_table.setCornerButtonEnabled(False)
        self.highlight_table.setColumnCount(6)
        self.highlight_table.setObjectName("highlight_table")
        self.highlight_table.setColumnCount(6)
        self.highlight_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.highlight_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.highlight_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.highlight_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.highlight_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.highlight_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.highlight_table.setHorizontalHeaderItem(5, item)
        self.highlight_table.horizontalHeader().setHighlightSections(False)
        self.highlight_table.horizontalHeader().setMinimumSectionSize(22)
        self.highlight_table.horizontalHeader().setSortIndicatorShown(True)
        self.highlight_table.verticalHeader().setDefaultSectionSize(22)
        self.highlight_table.verticalHeader().setHighlightSections(True)
        self.highlight_table.verticalHeader().setMinimumSectionSize(22)
        self.verticalLayout_4.addWidget(self.highlight_table)
        self.views.addWidget(self.highlights_pg)
        self.verticalLayout_2.addWidget(self.views)
        Base.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(Base)
        self.statusbar.setObjectName("statusbar")
        Base.setStatusBar(self.statusbar)
        self.tool_bar = QtGui.QToolBar(Base)
        self.tool_bar.setWindowTitle("toolBar")
        self.tool_bar.setMovable(True)
        self.tool_bar.setAllowedAreas(QtCore.Qt.BottomToolBarArea|QtCore.Qt.TopToolBarArea)
        self.tool_bar.setIconSize(QtCore.QSize(32, 32))
        self.tool_bar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.tool_bar.setObjectName("tool_bar")
        Base.addToolBar(QtCore.Qt.TopToolBarArea, self.tool_bar)
        self.act_english = QtGui.QAction(Base)
        self.act_english.setCheckable(True)
        self.act_english.setChecked(False)
        self.act_english.setObjectName("act_english")
        self.act_greek = QtGui.QAction(Base)
        self.act_greek.setCheckable(True)
        self.act_greek.setChecked(False)
        self.act_greek.setObjectName("act_greek")
        self.act_view_book = QtGui.QAction(Base)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/stuff/files_view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_view_book.setIcon(icon1)
        self.act_view_book.setObjectName("act_view_book")

        self.retranslateUi(Base)
        self.views.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Base)

    def retranslateUi(self, Base):
        self.file_table.setSortingEnabled(True)
        self.file_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Base", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.file_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Base", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.file_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Base", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.file_table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Base", "Percent", None, QtGui.QApplication.UnicodeUTF8))
        self.file_table.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Base", "Modified", None, QtGui.QApplication.UnicodeUTF8))
        self.file_table.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Base", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.fold_btn.setText(QtGui.QApplication.translate("Base", "Hide Book Info", None, QtGui.QApplication.UnicodeUTF8))
        self.time_lbl.setText(QtGui.QApplication.translate("Base", "Total time", None, QtGui.QApplication.UnicodeUTF8))
        self.title_lbl.setText(QtGui.QApplication.translate("Base", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.series_lbl.setText(QtGui.QApplication.translate("Base", "Series", None, QtGui.QApplication.UnicodeUTF8))
        self.author_lbl.setText(QtGui.QApplication.translate("Base", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.pages_lbl.setText(QtGui.QApplication.translate("Base", "Pages", None, QtGui.QApplication.UnicodeUTF8))
        self.lang_lbl.setText(QtGui.QApplication.translate("Base", "Language", None, QtGui.QApplication.UnicodeUTF8))
        self.status_lbl.setText(QtGui.QApplication.translate("Base", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.highlight_table.setSortingEnabled(True)
        self.highlight_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Base", "Highlight", None, QtGui.QApplication.UnicodeUTF8))
        self.highlight_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Base", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.highlight_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Base", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.highlight_table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Base", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.highlight_table.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Base", "Page", None, QtGui.QApplication.UnicodeUTF8))
        self.highlight_table.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Base", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.act_english.setText(QtGui.QApplication.translate("Base", "English", None, QtGui.QApplication.UnicodeUTF8))
        self.act_greek.setText(QtGui.QApplication.translate("Base", "Greek", None, QtGui.QApplication.UnicodeUTF8))
        self.act_view_book.setText(QtGui.QApplication.translate("Base", "View Book", None, QtGui.QApplication.UnicodeUTF8))
        self.act_view_book.setShortcut(QtGui.QApplication.translate("Base", "Ctrl+B", None, QtGui.QApplication.UnicodeUTF8))

from main import DropTableWidget
import images_rc
