# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Apps\DEV\PROJECTS\KoHighlights\gui_sync_group.ui',
# licensing of 'D:\Apps\DEV\PROJECTS\KoHighlights\gui_sync_group.ui' applies.
#
# Created: Tue May  7 14:53:08 2024
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_SyncGroup(object):
    def setupUi(self, SyncGroup):
        SyncGroup.setObjectName("SyncGroup")
        SyncGroup.resize(672, 50)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(SyncGroup)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(SyncGroup)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.power_btn = QtWidgets.QToolButton(self.frame)
        self.power_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/stuff/power32gray.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/stuff/power32red.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.power_btn.setIcon(icon)
        self.power_btn.setIconSize(QtCore.QSize(16, 16))
        self.power_btn.setCheckable(True)
        self.power_btn.setChecked(True)
        self.power_btn.setAutoRaise(True)
        self.power_btn.setObjectName("power_btn")
        self.verticalLayout.addWidget(self.power_btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_5.addWidget(self.frame)
        self.group_frm = QtWidgets.QFrame(SyncGroup)
        self.group_frm.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.group_frm.setFrameShape(QtWidgets.QFrame.Box)
        self.group_frm.setFrameShadow(QtWidgets.QFrame.Plain)
        self.group_frm.setLineWidth(1)
        self.group_frm.setObjectName("group_frm")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.group_frm)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title_frm = QtWidgets.QFrame(self.group_frm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_frm.sizePolicy().hasHeightForWidth())
        self.title_frm.setSizePolicy(sizePolicy)
        self.title_frm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frm.setObjectName("title_frm")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.title_frm)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.refresh_btn = QtWidgets.QToolButton(self.title_frm)
        self.refresh_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/stuff/refresh16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh_btn.setIcon(icon1)
        self.refresh_btn.setIconSize(QtCore.QSize(16, 16))
        self.refresh_btn.setChecked(False)
        self.refresh_btn.setAutoRaise(True)
        self.refresh_btn.setObjectName("refresh_btn")
        self.horizontalLayout_4.addWidget(self.refresh_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.title_lbl = QtWidgets.QLabel(self.title_frm)
        self.title_lbl.setAutoFillBackground(True)
        self.title_lbl.setText("")
        self.title_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.title_lbl.setObjectName("title_lbl")
        self.horizontalLayout_4.addWidget(self.title_lbl)
        spacerItem3 = QtWidgets.QSpacerItem(161, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.sync_btn = QtWidgets.QToolButton(self.title_frm)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/stuff/sync.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sync_btn.setIcon(icon2)
        self.sync_btn.setChecked(False)
        self.sync_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.sync_btn.setAutoRaise(True)
        self.sync_btn.setObjectName("sync_btn")
        self.horizontalLayout_4.addWidget(self.sync_btn)
        self.verticalLayout_2.addWidget(self.title_frm)
        self.checks_frm = QtWidgets.QFrame(self.group_frm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checks_frm.sizePolicy().hasHeightForWidth())
        self.checks_frm.setSizePolicy(sizePolicy)
        self.checks_frm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.checks_frm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.checks_frm.setObjectName("checks_frm")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.checks_frm)
        self.horizontalLayout.setContentsMargins(4, 0, 2, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sync_pos_chk = QtWidgets.QCheckBox(self.checks_frm)
        self.sync_pos_chk.setObjectName("sync_pos_chk")
        self.horizontalLayout.addWidget(self.sync_pos_chk)
        self.merge_chk = QtWidgets.QCheckBox(self.checks_frm)
        self.merge_chk.setObjectName("merge_chk")
        self.horizontalLayout.addWidget(self.merge_chk)
        self.sync_db_chk = QtWidgets.QCheckBox(self.checks_frm)
        self.sync_db_chk.setObjectName("sync_db_chk")
        self.horizontalLayout.addWidget(self.sync_db_chk)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.fold_btn = QtWidgets.QToolButton(self.checks_frm)
        self.fold_btn.setStyleSheet("QToolButton{border:none;}")
        self.fold_btn.setCheckable(True)
        self.fold_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.fold_btn.setArrowType(QtCore.Qt.DownArrow)
        self.fold_btn.setObjectName("fold_btn")
        self.horizontalLayout.addWidget(self.fold_btn)
        self.verticalLayout_2.addWidget(self.checks_frm)
        self.items_frm = QtWidgets.QFrame(self.group_frm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.items_frm.sizePolicy().hasHeightForWidth())
        self.items_frm.setSizePolicy(sizePolicy)
        self.items_frm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.items_frm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.items_frm.setObjectName("items_frm")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.items_frm)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2.addWidget(self.items_frm)
        self.horizontalLayout_5.addWidget(self.group_frm)

        self.retranslateUi(SyncGroup)
        QtCore.QObject.connect(self.power_btn, QtCore.SIGNAL("toggled(bool)"), self.group_frm.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(SyncGroup)

    def retranslateUi(self, SyncGroup):
        self.power_btn.setToolTip(QtWidgets.QApplication.translate("SyncGroup", "Enable or disable this Sync Group", None, -1))
        self.power_btn.setStatusTip(QtWidgets.QApplication.translate("SyncGroup", "Enable or disable this Sync Group", None, -1))
        self.refresh_btn.setToolTip(QtWidgets.QApplication.translate("SyncGroup", "Reload the Group and check the paths for errors", None, -1))
        self.refresh_btn.setStatusTip(QtWidgets.QApplication.translate("SyncGroup", "Reload the Group and check the paths for errors", None, -1))
        self.sync_btn.setToolTip(QtWidgets.QApplication.translate("SyncGroup", "Start the sync/merge process for this group", None, -1))
        self.sync_btn.setStatusTip(QtWidgets.QApplication.translate("SyncGroup", "Start the sync/merge process for this group", None, -1))
        self.sync_btn.setText(QtWidgets.QApplication.translate("SyncGroup", "Sync this group", None, -1))
        self.sync_pos_chk.setToolTip(QtWidgets.QApplication.translate("SyncGroup", "Sync the current position and read percent of the books", None, -1))
        self.sync_pos_chk.setStatusTip(QtWidgets.QApplication.translate("SyncGroup", "Sync the current position and read percent of the books", None, -1))
        self.sync_pos_chk.setText(QtWidgets.QApplication.translate("SyncGroup", "Sync position", None, -1))
        self.merge_chk.setToolTip(QtWidgets.QApplication.translate("SyncGroup", "Merge the highlights from both books\\n(and/or the archived version)", None, -1))
        self.merge_chk.setStatusTip(QtWidgets.QApplication.translate("SyncGroup", "Merge the highlights from both books\\\\n(and/or the archived version)", None, -1))
        self.merge_chk.setText(QtWidgets.QApplication.translate("SyncGroup", "Merge Highlights", None, -1))
        self.sync_db_chk.setToolTip(QtWidgets.QApplication.translate("SyncGroup", "Keep a synced version of the book in the archived database", None, -1))
        self.sync_db_chk.setStatusTip(QtWidgets.QApplication.translate("SyncGroup", "Keep a synced version of the book in the archived database", None, -1))
        self.sync_db_chk.setText(QtWidgets.QApplication.translate("SyncGroup", "Sync with archived", None, -1))
        self.fold_btn.setText(QtWidgets.QApplication.translate("SyncGroup", "Hide sync paths", None, -1))

import images_rc
